_layout: "patternbot_pattern_internal"
_extra_css:
  - 'modules/modules.min.css'
  - 'utilities/utilities.min.css'

title: "Modules"
description: |
  [Modulifier](++modulifier-settings-url++) generates a series of simple, default CSS components that can be used throughout the site, or as basic building blocks for more complex patterns.

patterns:
  images-embeds:
    title: "Images & embed containers"
    description: |
      Embed containers should be used for all content images, enforcing aspect ratios but also giving browsers a placeholder for the graphic before it loads to prevent unnecessary text reflows.
    _popout_button: false
    _resizable: false
    _code_sample: |
      <div class="embed embed-4by3">
        <img class="embed-item" src="/images/4by3.jpg" alt="">
      </div>
  media-objects:
    title: "Media objects"
    description: |
      A simple pattern that provides and image beside some text—good for comments with avatars and many other situations. Will usually be combined into larger patterns.
    _popout_button: false
    _resizable: false
    _code_sample: |
      <div class="media">
        <div class="media-img">
          <img src="/images/square.jpg" alt="">
        </div>
        <div class="media-body">
          <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
        </div>
      </div>
  skip-links:
    title: "Skip links"
    description: |
      A helpful accessibility feature that should be included immediately within the `<body>` tag on the top of most pages.
    _popout_button: false
    _resizable: false
    _code_sample: |
      <ul class="skip-links">
        <li><a href="#main">Jump to main content</a></li>
        <li><a href="#nav">Jump to main navigation</a></li>
        <li><a href="#pause">Pause all animations</a></li>
      </ul>
  utility-classes:
    title: "Utility classes"
    description: |
      All the different utility classes available from within [Modulifier](++modulifier-settings-url++).
    _popout_button: false
    _code: false
    _resizable: false

