_layout: "patternbot_pattern_internal"
_extra_css:
  - 'utilities/utilities.min.css'

patterns:
  classes:
    title: "Classes"
    description: "There are many utility classes available to all patterns & pages that help to quickly style elements without contributing to extra code duplication."
    _popout_button: false
    _resizable: false
    _code: false
  variables:
    title: "Variables"
    description: "There are some utility variables available to all patterns & pages that help to quickly style elements without contributing to extra code duplication."
    _popout_button: false
    _resizable: false
    _code: false
